### ISSUE TITLE
Use externally managed redis connection like poolboy 

### ISSUE THREAD

**Issue by lafka** [joakimk/toniq#10]
Currently you must define a  static configured redis host using `redis_url`. 
There should be a way to manage this externally using poolboy or similar.

I'v made a patch (https://github.com/lafka/toniq/tree/lafka-inject-uri) that enables this future.
If your up for it I'll make a pull request but you'v mentioned that you might be switching to Redix so I'm holding of until that's decided.

**Comment by joakimk** [comment]
I looked a bit at your patch, but it's a lot of code to take in and I don't have the time right now. I'll try and get back to it.

I'm not against making the redis client configurable, but I guess I'd like to know if there is a real use case for it. The only downside I can see with using the existing client is that you possibly have one more connection to your redis instance than if you reused an existing client.

**Comment by lafka** [comment]
Sorry i messed a bit more around with the branch after the initial push.... had to get it working when packaging a release, should have made a PR but wanted to check with if you had any opinions.

The problem with the current code is that I'm required to know the address of the Redis server before i start Toniq. In my case i get the Redis address from a service discovery app at runtime.

I can fix this in different ways but as i see it the cleanest approach is to allow managing the redis connection externally. The biggest change being removing `RedisConnection` and wrapping all the Exredis calls in `call_with_redis_worker fn(pid) -> ..` or similar.

**Comment by joakimk** [comment]
I wonder, would it be possible for you to start toniq later in your app when you know which redis server to use? At that point you could simply do `Application.put_env(:toniq, :redis_url, url, persistent: true)`.

`RedisConnection` could have a configurable delay before it reads :redis_url and tries to connect?

Toniq is not really designed to wait round for a connection to appear, it sort of needs to be able to crash and reboot on any errors to ensure it's running when needed.

**Comment by lafka** [comment]
Yeah definitely possible. I prefer patching your code though, for the simple reason that all application dependencies will be defined in mix/reltool instead of a some definitions scattered around in the code.

crash-and-burn semantics still applies. The difference being in the old code `RedisConnection` would block until connection was made, now it blocks until some user defined function (like setting up a pool) and/or `RedisConnection` has completed. The Exredis calls will fail in the same way

I'll keep my fork for now and if i get down to making a more solid solution I can get back to you, but for now I don't have enough time on my hand.

**Comment by joakimk** [comment]
I prefer not to make a general purpose tool more complex to maintain for a uncommon use-case.

I looked a bit at this problem. I don't know exactly your context, but it seems like a callback could work? https://github.com/joakimk/toniq/commit/7119d65e5b367766bda4a1e1b68d9f8099120bae

**Comment by lafka** [comment]
It helps, i can create some empty applications to ensure everything is started in order.

**Comment by joakimk** [comment]
Added redis_url_provider to master and released at 1.0.4.

**Comment by lafka** [comment]
Works, thanks :)

2016-02-20 9:05 GMT+00:00 Joakim Kolsjö notifications@github.com:

> Added redis_url_provider to master and released at 1.0.4.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/joakimk/toniq/issues/10#issuecomment-186545682.

## 

Med Vennlig Hilsen
Olav Frengstad

Systemutvikler // FWT
+47 920 42 090
