### ISSUE TITLE
Handle Redis unavailability

### ISSUE THREAD

**Issue by junekiwi** [joakimk/toniq#12]
Hey,
(I'm relatively new to Elixir so pardon me if I missed something).

I'm using toniq in a Phoenix app but if I stop Redis, it exit toniq.

``` elixir
[error] GenServer Toniq.Takeover terminating
** (FunctionClauseError) no function clause matching in Exredis.query/2
    lib/exredis.ex:109: Exredis.query(nil, ["SMEMBERS", "toniq:registered_vms"])
    (toniq) lib/toniq/takeover.ex:21: Toniq.Takeover.handle_info/2
    (stdlib) gen_server.erl:615: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:681: :gen_server.handle_msg/5
    (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Last message: :check_takeover
```

Shouldn't it handle such cases by restarting automatically as soon as the Redis server is back online ? Or is it the expected behavior ?

Thanks

**Comment by joakimk** [comment]
It does crash and restart a few times to see if it can reconnect to redis. The supervision config can be seen here https://github.com/joakimk/toniq/blob/master/lib/toniq.ex#L66.

You can see it in action if you ctrl + z your redis-server or just restart it quickly.

If this actually becomes a problem in production for anyone we could maybe add a sleep before each retry.

**Comment by junekiwi** [comment]
Ah yes I understand, thanks !
