### ISSUE TITLE
Keep mix task running until the contents of the queue is empty?

### ISSUE THREAD

**Issue by aphillipo** [joakimk/toniq#13]
Loving the work on Toniq...

I'm using it from a mix task... what is the best way to leave the mix task running until the contents of the queue is empty?  I'm not very good at Elixir (yet!) so excuse me probably misunderstanding the problem :-)  Currently a :timer.sleep(100_000) at the end of my task seem to suffice, but this is obviously not correct!

**Comment by joakimk** [comment]
Generally I'd keep a count going, the expected number of jobs and the number ran so far. You can maybe use https://github.com/joakimk/toniq/blob/master/test/benchmark.exs for inspiration.
