### ISSUE TITLE
Issue with using exrm.

### ISSUE THREAD

**Issue by blisscs** [joakimk/toniq#15]
Hello I am using toniq with exrm.
Everything is running ok when doing things in development.
But when I started doing in release I see this issue -

`[error] GenServer Toniq.Takeover terminating
** (UndefinedFunctionError) undefined function Mix.env/0 (module Mix is not available)
    Mix.env()
    (toniq) lib/toniq/takeover.ex:43: Toniq.Takeover.handle_missing_vm/2
    (toniq) lib/toniq/takeover.ex:23: Toniq.Takeover.handle_info/2
    (stdlib) gen_server.erl:615: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:681: :gen_server.handle_msg/5
    (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3`

Thank you for your help
I am really appreciated.

My mix.exs is as follow -
`defmodule Warehouse.Mixfile do
  use Mix.Project

  def project do
    [app: :warehouse,
     version: "0.0.9",
     elixir: "~> 1.0",
     elixirc_paths: elixirc_paths(Mix.env),
     compilers: [:phoenix, :gettext] ++ Mix.compilers,
     build_embedded: Mix.env == :prod,
     start_permanent: Mix.env == :prod,
     aliases: aliases,
     deps: deps]
  end

  # Configuration for the OTP application.
  #
  # Type `mix help compile.app` for more information.
  def application do
    [mod: {Warehouse, []},
     applications: [:phoenix, :phoenix_html, :cowboy, :logger, :gettext,
                    :phoenix_ecto, :postgrex, :comeonin, :arc, :arc_ecto, :toniq, :uuid]]
  end

  # Specifies which paths to compile per environment.
  defp elixirc_paths(:test), do: ["lib", "web", "test/support"]
  defp elixirc_paths(_),     do: ["lib", "web"]

  # Specifies your project dependencies.
  #
  # Type `mix help deps` for examples and options.
  defp deps do
    [{:phoenix, "~> 1.1.2"},
     {:phoenix_ecto, "~> 2.0"},
     {:postgrex, ">= 0.0.0"},
     {:phoenix_html, "~> 2.3"},
     {:phoenix_live_reload, "~> 1.0", only: :dev},
     {:gettext, "~> 0.9"},
     {:comeonin, "~> 2.1"},
     {:arc, "~> 0.3.0", override: true},
     {:arc_ecto, "~> 0.3.1"},
     {:exrm, "~> 0.19.9"},
     {:csvlixir, "~> 2.0"},
     {:toniq, "~> 1.0"},
     {:cowboy, "~> 1.0"}]
  end

  # Aliases are shortcut or tasks specific to the current project.
  # For example, to create, migrate and run the seeds file at once:
  #
  #     $ mix ecto.setup
  #
  # See the documentation for `Mix` for more info on aliases.
  defp aliases do
    ["ecto.setup": ["ecto.create", "ecto.migrate", "run priv/repo/seeds.exs"],
     "ecto.reset": ["ecto.drop", "ecto.setup"]]
  end
end`

**Comment by blisscs** [comment]
I have wrote a pull request https://github.com/joakimk/toniq/pull/16 to make this temporary work. Please see we might have to put something else there to get the enviroment reading.

**Comment by joakimk** [comment]
I'll close this and we'll keep the pull req for tracking this issue.
