### ISSUE TITLE
Guarantees around enqueuing

### ISSUE THREAD

**Issue by jclem** [joakimk/toniq#48]
It appears that Toniq doesn't have guarantees that a job is actually staged—for example, when calling `Tonic.enqueue/2`, the job is staged with `GenServer.cast/2`, and the job itself is then returned. If the `GenServer.cast/2` fails, we wouldn't necessarily ever know. Is this a correct interpretation of the current behavior?

**Comment by joakimk** [comment]
The first thing we do is to persist the job in redis. If JobRunner later crashes it will restart all of Toniq which should make the takeover system import the old job and try again.

But please clone the Toniq repo and try to break the JobRunner and see what happens :)

**Comment by jclem** [comment]
Yup! Sorry about that—I misread some code and thought that `enqueue` just `cast` and then returned.

**Comment by joakimk** [comment]
No problems. Thanks for using Toniq and for asking :)
