### ISSUE TITLE
Why use redis to persist data instead of already available ets?

### ISSUE THREAD

**Issue by shankardevy** [joakimk/toniq#5]
Hi
I am interested to know why you require redis database for persisting the data when the erlang ecosystem already provides a k/v store such as ets? It's not immediately obvious when and why should someone use redis.

Thanks

**Comment by benwilson512** [comment]
I imagine it's because ETS won't survive node reboots. While ets and such allow code servers to hold a lot more state than they would in say, a Rails app it's still pretty common to be wary of having your code server be the ONLY canonical store of such data.

**Comment by joakimk** [comment]
Hello!

For some reason I didn't get a notification, or I missed it.

My primary use-case for Toniq is phoenix apps running on heroku where the app code is restarted every day and there is no way to use distributed erlang to communicate between nodes. Redis is available on heroku and is very familiar to many people, me included, so I used that.

Toniq could support other persistence methods in the future if needed.
