### ISSUE TITLE
Documention

### ISSUE THREAD

**Issue by benwilson512** [joakimk/toniq#8]
Hey!

So I've been going through the code in toniq just to get a feel for how it works, and that could be helped a lot by providing some documentation on each of the modules. For example I'm still unclear right now how it's getting tasks from Redis, I think that's the Job Importer, but I'm not 100% sure. In any case, at least some module docs in each would go a long way towards helping.

**Comment by joakimk** [comment]
Hello! Thanks for you interest in toniq. [contributions](https://github.com/joakimk/toniq#contributing) are welcome as you figure it out of course but I'll try and keep it in mind next time I work on toniq.

The normal flow is: enqueue -> store in redis -> run job -> remove from redis

Redis is just a backup. The reason for this backup is that you should be able to restart the server, or loose the connection to redis and still have the jobs run at some point. This is where the JobImporter is used.
